version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
      - ./pdfs:/usr/src/app/pdfs
      # - ./data.db:/usr/src/app/data.db
      - ./lookup.csv:/usr/src/app/lookup.csv
      - ./mapToProducts.csv:/usr/src/app/mapToProducts.csv
    ports:
      - "8000:8000"
